### PR TITLE
[Bugfix:System] Set CMAKE_CXX_STANDARD

### PR DESCRIPTION
**Pull request by MasterOdin**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?

When attempting to build the library on my macOS using clang 13, I get 68 warnings and 20 errors, with this being the bottom most snippet:

```
/Users/mpeveler/code/github/submitty/AnalysisToolsTS/include/json/include/nlohmann/detail/meta/cpp_future.hpp:142:28: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using index_sequence_for = make_index_sequence<sizeof...(Ts)>;
                           ^
/Users/mpeveler/code/github/submitty/AnalysisToolsTS/include/json/include/nlohmann/detail/meta/cpp_future.hpp:156:33: error: unknown type name 'constexpr'
    static JSON_INLINE_VARIABLE constexpr T value{};
                                ^
/Users/mpeveler/code/github/submitty/AnalysisToolsTS/include/json/include/nlohmann/detail/meta/cpp_future.hpp:156:44: error: expected ';' at end of declaration list
    static JSON_INLINE_VARIABLE constexpr T value{};
                                           ^
                                           ;
/Users/mpeveler/code/github/submitty/AnalysisToolsTS/include/json/include/nlohmann/detail/meta/cpp_future.hpp:161:5: error: unknown type name 'constexpr'
    constexpr T static_const<T>::value;
    ^
/Users/mpeveler/code/github/submitty/AnalysisToolsTS/include/json/include/nlohmann/detail/meta/cpp_future.hpp:161:15: warning: variable templates are a C++14 extension [-Wc++14-extensions]
    constexpr T static_const<T>::value;
```

Each of the warnings / errors have a `-Wc++11-extensions` or `-Wc++14-extensions` mention, and so looking around, it looks like clang requires explicitly setting the version of C++ you want to compile against, defaulting to something older than C++11?

g++ does not have this issue, and compiles just fine out of the box.

### What is the new behavior?

By setting the `CMAKE_CXX_STANDARD` to C++14, both clang and g++ compile fine. I'm not sure if there's any potential downside of including this, other than if new C++ features are included, this line would need to be incremented to that new version. I'm not sure what support for C++17 or C++20 is amongst compilers to know if a newer version should be specified.

### CODE REVIEW

**Comment by MasterOdin** [comment]
I've updated the test workflow to verify we can build and test alright on both ubuntu and macos, which verifies that this change is working as expected.  See https://github.com/Submitty/AnalysisToolsTS/actions/runs/2840517861 as an example of the workflow change without also setting the the `CMAKE_CXX_STANDARD`, and that the `macos-latest` run fails.

Note, it seems like this is something specific to macOS clang, where when using clang on ubuntu-latest, the build works as expected without having to set `CMAKE_CXX_STANDARD`.

**Comment by poorna2152** [comment]
Thanks for catching this. I'm guessing the tests are failing currently because I'm running `python testRunner.py` in the action file and it should be fixed to `python3 testRunner.py`. https://github.com/Submitty/AnalysisToolsTS/blob/main/.github/workflows/test.yml#L15

**Review by poorna2152 — APPROVED** [review]

**Comment by MasterOdin** [comment]
> Thanks for catching this. I'm guessing the tests are failing currently because I'm running python testRunner.py in the action file and it should be fixed to python3 testRunner.py.

The test is failing because the previous step (building the binaries) fails, but there's no sufficient error checking in the bash script to catch and bubble that up. The easiest way would be to do `set -e` where if any command then has a non-zero exit code, it will cause the script to immediately return with a non-zero exit code. Changing the `python` to `python3` has no effect on that.

**Comment by poorna2152** [comment]
I thought the building was properly done there. https://github.com/Submitty/AnalysisToolsTS/runs/7789047623?check_suite_focus=true#step:4:320
And thought the error was due to subprocess run only being available after python 3.5. https://stackoverflow.com/questions/40590192/getting-an-error-attributeerror-module-object-has-no-attribute-run-while

**Pull request merged**
